/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.backcaps.vehiclemanagement;

import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author MacBookPro
 */
public class ApprovalForm extends javax.swing.JFrame {
    
    
    //Iterate with navigators to check what is the current position
    int currentPosition=0;
    
    //automatic increment id whenever a Role record is entered
    int autoID;
    
    Person_Controller controller;
    /**
     * Creates new form RoleManagementForm
     */
    public ApprovalForm() {
        initComponents();
        autoID = 0;
        controller = new Person_Controller();
        List<String> list = controller.getRolesFromList(this);
        for(String x: list){
            roleSet.addItem(x);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moveToFirst = new javax.swing.JButton();
        moveToLast = new javax.swing.JButton();
        moveOneLeft = new javax.swing.JButton();
        moveOneRight = new javax.swing.JButton();
        currentStatus = new javax.swing.JLabel();
        deleteRole = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        findRole = new javax.swing.JButton();
        saveRecord = new javax.swing.JButton();
        cancelRecord1 = new javax.swing.JButton();
        saveSuccess = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        roleSet = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        moveToFirst.setText("<<");
        moveToFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveToFirstActionPerformed(evt);
            }
        });

        moveToLast.setText(">>");
        moveToLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveToLastActionPerformed(evt);
            }
        });

        moveOneLeft.setText("<");
        moveOneLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneLeftActionPerformed(evt);
            }
        });

        moveOneRight.setText(">");
        moveOneRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneRightActionPerformed(evt);
            }
        });

        currentStatus.setText("0");

        deleteRole.setText("Regect");
        deleteRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRoleActionPerformed(evt);
            }
        });

        jLabel1.setText("Person Username:");

        jLabel2.setText("Person Name:");

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        findRole.setText("Find");
        findRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findRoleActionPerformed(evt);
            }
        });

        saveRecord.setText("Approve");
        saveRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRecordActionPerformed(evt);
            }
        });

        cancelRecord1.setText("Go Back");
        cancelRecord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRecord1ActionPerformed(evt);
            }
        });

        saveSuccess.setText(" ");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel3.setText("Registeration Approval");

        jLabel4.setText("Set Role:");

        roleSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleSetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idField)
                            .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(moveToFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moveOneLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(currentStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moveOneRight)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveSuccess))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(roleSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(moveToLast)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(saveRecord)
                        .addGap(104, 104, 104)
                        .addComponent(deleteRole)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelRecord1)
                    .addComponent(findRole))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findRole))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveSuccess)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(roleSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteRole)
                    .addComponent(saveRecord))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moveToLast)
                    .addComponent(moveOneRight)
                    .addComponent(currentStatus)
                    .addComponent(moveOneLeft)
                    .addComponent(moveToFirst)
                    .addComponent(cancelRecord1))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // a function to set field values on press of specific buttons 
    void setFieldsFromListAt(int index){
        if(controller.searchPerson(index, this)!=null){
            Person nPassenger = new Person();
            nPassenger = controller.searchPerson(index,this);
            idField.setText(nPassenger.getUserName()+"");
            nameField.setText(nPassenger.getName());
        }
        else {
            currentPosition =0;
            setFieldsFromListAt(0);
        }
    }
    void resetFields(){
        idField.setText("");
        nameField.setText("");
    }
    private void deleteRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRoleActionPerformed
        // TODO add your handling code here:
        if(controller!=null){
                controller.delPerson(currentPosition,this);
                resetFields();
        }
        resetFields();
        currentStatus.setText("0");
        currentPosition =0;
        if(controller!=null && controller.getSizeApproval(this)!=0){
            setFieldsFromListAt(currentPosition);
        }
    }//GEN-LAST:event_deleteRoleActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void findRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findRoleActionPerformed
        // TODO add your handling code here:
        saveSuccess.setText("");
        if(controller!=null){
            int position = controller.searchPerson(nameField.getText(),this);
            if(position!=-1){
                currentPosition = position;
                setFieldsFromListAt(currentPosition);
                currentStatus.setText(currentPosition+"");
            }
        }
    }//GEN-LAST:event_findRoleActionPerformed

    private void saveRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRecordActionPerformed
        // TODO add your handling code here:
        // check if the id or name fields are not empty
        if(!"".equals(idField.getText()) && !"".equals(nameField.getText())){
            Person nPassenger = new Person();
            nPassenger = controller.searchPerson(currentPosition,this);
            if(controller==null) controller = new Person_Controller();
            controller.approvePerson(nPassenger,roleSet.getSelectedItem().toString(),this);
            idField.setText(autoID+"");
            nameField.setText("");
            controller.delPerson(currentPosition,this);
        }
        else{
            showMessageDialog(null, "Some fields are missing or there is some other exception", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveRecordActionPerformed
    
    private void cancelRecord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRecord1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new AdminDashboard().setVisible(true);
        resetFields();
        
    }//GEN-LAST:event_cancelRecord1ActionPerformed

    private void moveOneLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneLeftActionPerformed
        // TODO add your handling code here:
        if(currentPosition!=0){
            currentPosition--;
        }
        setFieldsFromListAt(currentPosition);
        currentStatus.setText(currentPosition+"");
        saveSuccess.setText("");
    }//GEN-LAST:event_moveOneLeftActionPerformed

    private void moveOneRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneRightActionPerformed
        // TODO add your handling code here:
        if(controller!=null){
            if(currentPosition!=controller.getSizeApproval(this)-1){
                currentPosition++;
            }
            setFieldsFromListAt(currentPosition);
            currentStatus.setText(currentPosition+"");
            saveSuccess.setText("");
        }
    }//GEN-LAST:event_moveOneRightActionPerformed

    private void moveToFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveToFirstActionPerformed
        // TODO add your handling code here:
        currentPosition=0;
        currentStatus.setText(currentPosition+"");
        setFieldsFromListAt(currentPosition);
        saveSuccess.setText("");
    }//GEN-LAST:event_moveToFirstActionPerformed

    private void moveToLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveToLastActionPerformed
        // TODO add your handling code here:
        if(controller!=null){
            currentPosition = controller.getSizeApproval(this)-1;
            currentStatus.setText(currentPosition+"");
            setFieldsFromListAt(currentPosition);
        }
        saveSuccess.setText("");
    }//GEN-LAST:event_moveToLastActionPerformed

    private void roleSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleSetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApprovalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApprovalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApprovalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApprovalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApprovalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelRecord1;
    private javax.swing.JLabel currentStatus;
    private javax.swing.JButton deleteRole;
    private javax.swing.JButton findRole;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton moveOneLeft;
    private javax.swing.JButton moveOneRight;
    private javax.swing.JButton moveToFirst;
    private javax.swing.JButton moveToLast;
    private javax.swing.JTextField nameField;
    private javax.swing.JComboBox<String> roleSet;
    private javax.swing.JButton saveRecord;
    private javax.swing.JLabel saveSuccess;
    // End of variables declaration//GEN-END:variables
}
